import type { Product, ReorderDraft, SaleRecord } from "./types";

export const STORE_NAME = "Sharma Kirana, Karol Bagh";
export const STORE_OWNER = "Ramesh Sharma";

export const SEED_PRODUCTS: Product[] = [
  {
    _id: "prod_parle_g",
    sku: "BISC-PARLE-G-70",
    name: "Parle-G Biscuit 70g",
    nameHi: "Parle-G biscuit",
    aliases: ["parle g", "parle-g", "parle ji", "biscuit"],
    category: "snacks",
    unit: "pack",
    stock: 48,
    reorderLevel: 24,
    costPrice: 4,
    sellPrice: 5,
    embeddingText: "Parle-G glucose biscuit pack snacks",
  },
  {
    _id: "prod_maggi",
    sku: "NOOD-MAGGI-70",
    name: "Maggi Masala 70g",
    nameHi: "Maggi noodles",
    aliases: ["maggi", "noodles", "masala maggi"],
    category: "staples",
    unit: "pack",
    stock: 32,
    reorderLevel: 20,
    costPrice: 10,
    sellPrice: 14,
    embeddingText: "Maggi instant masala noodles",
  },
  {
    _id: "prod_dahi",
    sku: "DAIRY-DAHI-500",
    name: "Amul Fresh Curd 500g",
    nameHi: "Dahi",
    aliases: ["dahi", "curd", "yogurt", "doodh dahi"],
    category: "dairy",
    unit: "cup",
    stock: 6,
    reorderLevel: 12,
    costPrice: 28,
    sellPrice: 35,
    embeddingText: "dahi curd fresh yogurt dairy Amul",
  },
  {
    _id: "prod_milk",
    sku: "DAIRY-MILK-1L",
    name: "Amul Taaza Milk 1L",
    nameHi: "Doodh",
    aliases: ["doodh", "milk", "taaza"],
    category: "dairy",
    unit: "pkt",
    stock: 18,
    reorderLevel: 15,
    costPrice: 52,
    sellPrice: 58,
    embeddingText: "doodh milk taaza dairy litre",
  },
  {
    _id: "prod_sabun",
    sku: "HPC-LIFEBUOY-125",
    name: "Lifebuoy Soap 125g",
    nameHi: "Sabun",
    aliases: ["sabun", "soap", "lifebuoy"],
    category: "personal care",
    unit: "pc",
    stock: 22,
    reorderLevel: 10,
    costPrice: 28,
    sellPrice: 32,
    embeddingText: "sabun soap lifebuoy bathing",
  },
  {
    _id: "prod_chai",
    sku: "BEV-TAJ-250",
    name: "Taj Mahal Tea 250g",
    nameHi: "Chai patti",
    aliases: ["chai", "tea", "patti", "taj mahal"],
    category: "beverages",
    unit: "pack",
    stock: 14,
    reorderLevel: 8,
    costPrice: 180,
    sellPrice: 210,
    embeddingText: "chai tea patti Taj Mahal",
  },
  {
    _id: "prod_atta",
    sku: "STAPLE-ATTA-5KG",
    name: "Aashirvaad Atta 5kg",
    nameHi: "Atta",
    aliases: ["atta", "flour", "aashirvaad"],
    category: "staples",
    unit: "bag",
    stock: 9,
    reorderLevel: 5,
    costPrice: 240,
    sellPrice: 265,
    embeddingText: "atta wheat flour aashirvaad staple",
  },
  {
    _id: "prod_oil",
    sku: "STAPLE-OIL-1L",
    name: "Fortune Sunflower Oil 1L",
    nameHi: "Tel",
    aliases: ["tel", "oil", "sunflower", "fortune"],
    category: "staples",
    unit: "bottle",
    stock: 11,
    reorderLevel: 6,
    costPrice: 135,
    sellPrice: 150,
    embeddingText: "tel cooking oil sunflower fortune",
  },
];

export const SEED_SALES: SaleRecord[] = [
  {
    _id: "sale_1",
    productId: "prod_maggi",
    productName: "Maggi Masala 70g",
    quantity: 8,
    unit: "pack",
    spokenName: "maggi",
    resolvedVia: "alias",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: "sale_2",
    productId: "prod_milk",
    productName: "Amul Taaza Milk 1L",
    quantity: 5,
    unit: "pkt",
    spokenName: "doodh",
    resolvedVia: "vector_search",
    timestamp: new Date(Date.now() - 43200000).toISOString(),
  },
];

export function createInitialReorderDraft(): ReorderDraft | undefined {
  return undefined;
}
